/* Generated By:JavaCC: Do not edit this line. RunParserConstants.java */
package org.jchien.shuffle.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RunParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int SLASH = 8;
  /** RegularExpression Id. */
  int CARET = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int WORD = 12;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int SCORE_VALUE = 14;
  /** RegularExpression Id. */
  int RUN_HEADER = 15;
  /** RegularExpression Id. */
  int TEAM_HEADER = 16;
  /** RegularExpression Id. */
  int SCORE_HEADER = 17;
  /** RegularExpression Id. */
  int ITEMS_HEADER = 18;
  /** RegularExpression Id. */
  int MOVES_LEFT_HEADER = 19;
  /** RegularExpression Id. */
  int END_HEADER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"/\"",
    "\"^\"",
    "<DIGIT>",
    "<LETTER>",
    "<WORD>",
    "<NUM>",
    "<SCORE_VALUE>",
    "<RUN_HEADER>",
    "\"TEAM:\"",
    "\"SCORE:\"",
    "\"ITEMS:\"",
    "\"MOVES LEFT:\"",
    "\"!END\"",
  };

}
