/* Generated By:JavaCC: Do not edit this line. RunParserConstants.java */
package org.jchien.shuffle.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RunParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PERFECT = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int LEVEL = 8;
  /** RegularExpression Id. */
  int WORD = 9;
  /** RegularExpression Id. */
  int NUM = 10;
  /** RegularExpression Id. */
  int SLASH = 11;
  /** RegularExpression Id. */
  int RUN_HEADER = 12;
  /** RegularExpression Id. */
  int EB_HEADER = 13;
  /** RegularExpression Id. */
  int TEAM_HEADER = 14;
  /** RegularExpression Id. */
  int SCORE_HEADER = 15;
  /** RegularExpression Id. */
  int ITEMS_HEADER = 16;
  /** RegularExpression Id. */
  int MOVES_LEFT_HEADER = 17;
  /** RegularExpression Id. */
  int END_HEADER = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"PERFECT\"",
    "<DIGIT>",
    "<LETTER>",
    "<LEVEL>",
    "<WORD>",
    "<NUM>",
    "\"/\"",
    "\"!RUN\"",
    "\"!EB\"",
    "\"TEAM:\"",
    "\"SCORE:\"",
    "\"ITEMS:\"",
    "\"MOVES LEFT:\"",
    "\"!END\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\".\"",
  };

}
